version: '3.8'

services:
  prod_airtel_quiz_zbm_school_app:
    container_name: prod_airtel_quiz_zbm_school_app
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./app/:/app
    expose :
      - "3000"
    command: >
      sh -c "yarn install && yarn build && yarn start"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true