import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSession from "@/components/auth/AuthSession";
import DashboardLayout from "@/components/layouts/DashboardLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airtel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <AuthSession>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen   `}>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </body>
      </AuthSession>
    </html>
  );
}
